### ISSUE TITLE
Acconditionate Decidime Instance

### ISSUE THREAD

**Issue by microstudi** [Green-Party-of-Canada-Members/gpc-decidim#1]
- [x] Configure GIT
- [x] Configure Capistrano
- [x] Setup deploy documentation
- [x] Setup minimal functional tests & GH actions
- [x] Upgrade 24

**Comment by BigSnicker** [comment]
Great, we have contact!  Thanks!

**Comment by BigSnicker** [comment]
Random question.  I keep trying to do the v24-stable upgrade on the test server, but I keep running into the Doorkeeper 5.0 authentication problem, where the OAuth spec now requires tokens.

Is there an easy way around that, that might help me do the upgrade and offload that work from you?

**Comment by microstudi** [comment]
Better wait until I do it here, then is just a matter of applying the same gemfile

**Comment by microstudi** [comment]
@BigSnicker upgrade to 0.24 completed and deployed!
![image](https://user-images.githubusercontent.com/1401520/117292308-57f24f00-ae70-11eb-9367-07b8d6b675f6.png)

Should we close this?

**Comment by BigSnicker** [comment]
Amazing!!

We'll do our testing this weekend, but let's consider this closed.  Thanks for the great work.

On the other items, I'd recommend the following:

1. See if you have any recommendations on better solutions, particularly for how to securely share files with signed-in members.
2. If there's anything easy and clearly defined (i.e. 2 hours or under), just go ahead and do it
3. For anything larger (e.g. translation API), just attach your estimate of the amount of work to the item and we can help prioritize the issues based on the amount of work.

That make sense?

**Comment by BigSnicker** [comment]
Random beginner's question... is there any reason why I still get this?

```
decidim@gpcmembers:~/decidim-gpc/current$ decidim --version
0.23.3
```

**Comment by microstudi** [comment]
> Random beginner's question... is there any reason why I still get this?
> 
> ```
> decidim@gpcmembers:~/decidim-gpc/current$ decidim --version
> 0.23.3
> ```
> 
> I can see the site has v.24 working, I'm just interested why the above happens.

This is because decidim is the application installed globally in the system. It has no use a part from creating the initial decidim app. You can always update by doing "gem update decidim" OUTSIDE the decidim-gpc folder

I'll collect the total amount of hours spent till now and let you know. Not sure I have (or anyone) a solution for sharing files securely (I assume you mean only for logged in users). Probably better use gdoc or similar with secret links for now.

**Comment by BigSnicker** [comment]
Ahhh, great.  

Yes, please let us know where you're at with the hours, and I did mean only for logged-in users.

Regarding the GDoc "secret links", I just want to make sure I'm not missing something.  There isn't currently a way to make gdoc links only visible to logged-in users, I assume?
