### ISSUE TITLE
Create custom decidim branch for v0.27

### ISSUE THREAD

**Issue by microstudi** [Green-Party-of-Canada-Members/gpc-decidim#107]
- [x] Create branch `0.27-canada` in https://github.com/openpoke/decidim/ from branch `release/0.27-stable` (latest version)
- [x] Incorporate patches:
  - [x]  https://github.com/openpoke/decidim/pull/15
  - [x] https://github.com/openpoke/decidim/pull/13

**Comment by paarals** [comment]
closed in favour of #132
