### ISSUE TITLE
GD3 - FrontEnd vote action UI/implementation

### ISSUE THREAD

**Issue by microstudi** [Green-Party-of-Canada-Members/gpc-decidim#114]
Implementation of the overriden vote action, CSS & Javascript (if needed).

Made by https://github.com/openpoke/decidim-module-decidim_awesome/pull/14, the oprations of create and destroy a vote with weight are already working.

This spec is about getting the final design done according to:

- [ ] User Interface in Individual Proposals
The creation of a 3 card voting panel within individual proposals, including:
  a. Option to vote for Green, Yellow or Red, with a null state for not yet voted
  b. Vote totals are counted for each colour
  c. Vote totals are updated dynamically after user votes

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/1401520/93e2aaf5-407a-4ece-8d33-90fd9d422383)

When the user votes a proposal, a modal should be opened with a message:
![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/1401520/81de9674-cfbd-4686-a3af-3b7319452333)

- [ ] Modal text when user clicks on a voting card:
1. Green: “The green card means that you…and that you recommend that the Meeting…“
2. Yellow: “The yellow card means that you… and that you recommend that the Meeting….”
3. Red: “The red card means that you… and that you recommend that the Meeting… “
4. Each window could have “check here to not receive these messages in the future”, which stops messages for that specific component

- [ ] CardM proposal footer:
User Interface at Proposal Component level (“card view”)
1. Creation of ‘alphabetical proposal order’, and set it as the default
3. Users should not be able to vote from the higher level proposal component card view, but be directed to vote within individual proposals.
Alternative 1:
![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/1401520/40cc38e9-6f8e-4dc8-81c6-d58c759d16dc)
Alternative 2:
![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/1401520/dea5d3f6-fe12-47b4-8f8d-2c27df9ef4b9)

**Comment by BigSnicker** [comment]
If possible, we'd like to add the possibility of people to abstain. This would ideally include the following:

1. A web admin option, when setting up the votes, to indicate an abstention.
2. If a voter is allowed to abstain, it is shown differently than the other votes:
![Image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/e5ba3038-d24a-45c6-8d04-43b756977539)
