### ISSUE TITLE
Minor fixes

### ISSUE THREAD

**Issue by paarals** [Green-Party-of-Canada-Members/gpc-decidim#120]
**Making sure Abstention buttons are clear, readable and follow design principle:** 

- [x] Change the color of the "voted" button according to the color of the weight. Includes:
  - [x] Should be the color #8b898b
  - [x] In detailed proposal, should be solid grey
  Right now: 
  ![Image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/40388743/aa84a15e-2967-45e1-8274-a7141d5032ed)
  - [x] In overview proposal list, should be solid grey
  Right now:
  ![Image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/40388743/aba8445f-07ae-44ca-94ea-c7ec72e66a3a)
  Desired:
  ![Image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/40388743/8931d1e2-fb0a-41c7-bf93-d4d56b76b299)

  **Making sure the "Voted" button is red, when the participant votes red**

  - [x] In overview proposal list, should be solid red if the option is red
  Right now:
  ![Image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/40388743/515fe207-25ac-4f64-90bc-2e360f877609)
  Desired:
  ![Image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/40388743/7f1a7c7c-da2e-40dd-8c85-46c2a99ed14b)

**Preventing "Change my Vote" from triggering modal window:**

- [ ]  Prevent "Change my Vote" from triggering the modal window.  
Right now:
![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/19323bff-eae4-4bf7-8346-2d55a1dbd251)

Desired:
Modal window triggered every time a vote/support is made, but not when "Change my vote" is pressed.

**Specifying name of proposal in modal window:**

- [x]  Change "my vote is Green" to "my vote on %PROPOSAL_TITLE% is Green"
- [ ] 
![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/55491c80-e781-4724-b2eb-7b72126cf195)

Only if it's easy to do, you could add the proposal title to the modal window. 

**Making voting more visible to mobile clients:**

- [x]   Put Voting panel above Donate panel

When reading on mobile, participants will see the donate panel first and might not realize they have to scroll down further to see the voting panel.  Let's promote the Voting panel to the top, to ensure that mobile clients see it first.

**Removing Google crawling restriction:**

- [x]   Remove ROBOTS.txt restriction to search engines

We've decided to allow Google to index the site again.

**Add language-specific GPC logo:**

- [x]   Put the following locale-specific logos in the top left of the site
![gpc_logo_web_green_en](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/4033e6c4-f227-4655-b5c8-25d39d098004)

![gpc_logo_web_green_fr](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/f87cf92a-c80a-4078-a573-1297cf3fac9e)

**Verifying modal window compliance for the visually-impaired:**

- [x]   Ensure modal window meets standards for visually impaired 

I don' t know if this is an issue of not, but just wanted to be clear about the North American standard for how visually-impaired readers expect to have modal windows marked: "Active popups should include an "aria-modal" attribute that equals to "true", and a "role" attribute that equals to "dialog", so screen-reader users know how to navigate within it."

**Comment by BigSnicker** [comment]
Added a fix.

**Comment by BigSnicker** [comment]
I haven't verified the ROBOTS text or the visually-impaired reading, but everything looks great.  Closing the ticket.
