### ISSUE TITLE
Decidim awesome - Select default sort for a component

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#121]
As a second phase, we may want to be able to specify the "default sort" of a given component and/or the types of sort that are available to the participant.

**Comment by BigSnicker** [comment]
@Laurence-Montgomery reminded me that this is already available!

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/c8b973fb-2d50-41d4-82a2-f4f7e2963287)

**Comment by microstudi** [comment]
The default is implemented but the ability to choose which types of sorting is enabled in each component no
