### ISSUE TITLE
Alphabetical order in French puts accented characters at the end

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#129]
This isn't urgent, but ideally, the accented characters should be placed near their unaccented equivalents.

StackOverflow's take: https://stackoverflow.com/questions/68833336/flutter-sort-a-list-alphabetically-taking-accented-characters-into-account

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/50c3582d-b962-4942-b1b1-451ed1bf6ff3)

**Comment by paarals** [comment]
is that close @BigSnicker?

**Comment by BigSnicker** [comment]
Parfait!
