### ISSUE TITLE
Increasing PWA compliance and metadata by updating wedecide.green.ca/manifest.json

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#133]
After doing some testing on v.27 PWA functionality, here are some ideas to improve the metadata for a possble WeDecide PWA app.

Assets listed below are in this folder: https://drive.google.com/drive/folders/1Pttyzk39AHCUN2c3TueQlCE45WJYFNei?usp=sharing

The most important change is adding a "short_name", which is required for compliance and an SVG option for the icon.

Suggested changes to https://wedecide.green.ca/manifest.json.

Changes or additions are in bold.

{
 **"short_name": "WeDecide",**
 "lang": "en",
 **"id" : "https://wedecide.green.ca",**
 **"orientation" : "any",**
 **"name": "WeDecide: The Green Party of Canada's Participatory Democracy Engine",**
 **"enableNotifications" : "true",**
  **"icons": [
    {
      "src": "/images/WeDecideLogo-512x512.svg",
      "type": "image/svg+xml",
      "sizes": "512x512"
    },
    {
      "src": "/images/WeDecideLogo-192x192.png",
      "type": "image/png",
      "sizes": "192x192"
    },
    {
      "src": "/images/WeDecideLogo-512x512.png",
      "type": "image/png",
      "sizes": "512x512"
    }
  ],**
  "start_url" : "/",
  **"background_color" : "#3d9b35",**
  "display" : "standalone",
  **"scope" : "/",**
  **"theme_color" : "#3d9b35",**
  **"dir" : "ltr", **
  **"description": "WeDecide is the engine used by members of the Green Party of Canada to decide the future of the Green Party of Canada. It can be used by Party members to collaborate on the Party's policy and participate in internal elections.

Cette application peut également être utilisée en français."
]**

**Comment by BigSnicker** [comment]
Resolved by having @BigSnicker put changes in place directly as commits to the repo.

**Comment by paarals** [comment]
this guy @BigSnicker is pretty serious!
