### ISSUE TITLE
Conference Speaker Bios not working on mobile phones

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#135]
Unclear why the drawers used to show speaker bios are not working on any mobile phone.

Example: https://wedecide.green.ca/conferences/vgm-2023/speakers

**Comment by paarals** [comment]
fixed via #139

**Comment by BigSnicker** [comment]
Now that we've added speakers, this appears to be an issue again, for some cases.  

To reproduce
1. Go to speakers list on your mobile: https://wedecide.green.ca/conferences/vgm-2023/speakers
2. Click on last speaker.... "Jaden Braves"

**Comment by paarals** [comment]
fixed via #163
