### ISSUE TITLE
In-line images removed from proposal texts during v.27 upgrade

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#143]
Images in proposal body text disappeared during the v.27 upgrade.

For example, there should be an image of the candidate in the top left corner of this proposal text: https://wedecide.green.ca/processes/federal-council-elections-2023/f/447/proposals/3898

**Comment by microstudi** [comment]
It should be fixed now @BigSnicker

**Comment by BigSnicker** [comment]
Perfect!  Thank you.
