### ISSUE TITLE
Machine Translation not working

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#146]
Machine translation appears to have stopped working on Jan 14 or Jan 15.

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/c56cc829-4072-4fdc-bad5-e720429dd832)

**Comment by BigSnicker** [comment]
FYI, while this has been fixed, there is a period of time in which comments still have no translations. 

Example: https://wedecide.green.ca/processes/create-proposals/f/457/proposals/4322?locale=fr

Is there any way to retroactively fill in missing translations?

**Comment by microstudi** [comment]
I've executed a script to reprocess missing comments
