### ISSUE TITLE
Incorrect log-in panel when triggered by need for authorization

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#150]
Currently there are two types of log-ins, one from "Sign-in", which is correct....

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/100101da-96af-497b-a29f-f98b0bde16ec)

The other, which is opened when validation is required, is not correct, and it is causing people to try to enter their username and password information in the admin section...

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/108cb92b-1a2c-4aaf-8b49-3cd9864d4a57)

**Comment by Laurence-Montgomery** [comment]
This is causing some confusion for members who do not understand that they need to login at greenparty.ca They are trying to enter email/password (or even 'forgot your password') in this modal instead.

**Comment by microstudi** [comment]
applied the same solution as the general login
![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/1401520/8e226ec5-940c-4b2b-a408-6f2d6ffc19c8)

**Comment by paarals** [comment]
closed via #153
