### ISSUE TITLE
Amendments can be made to machine-translated text

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#152]
Issue: Amendments can be made to machine-translated text. This could distort the original proposal text.  Amendments should only be possible in the submitted (i.e. original) language of User Proposals.  Note: Amendments can be made to either side of Official Proposals.

To reproduce:

1. Take a proposal that has machine-translated text (https://staging.deploy.green.ca/processes/Policy2021/f/223/proposals/2583/?locale=fr)
2. Propose an amendment (e.g. "Modifier Proposition")
3. The proposal text opens with the machine translated text.

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/b959259e-c50b-449d-b571-9093c377bb3f)

The above proposal body text is machine-translated, and so should not be amendable.

**Comment by BigSnicker** [comment]
This is an amendment that was written based on the machine-translated text of a proposal: https://staging.deploy.green.ca/processes/Policy2021/f/223/proposals/2587

**Comment by paarals** [comment]
closed via #153
