### ISSUE TITLE
Repeated lines of machine-translated text [blocking]

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#154]
Lines of machine-translated text are sometimes repeated.  Examples are below. Note that this error is likely unrelated to the Serial Amendments feature, as similar behaviour was observed in earlier amendments.

The most reliable way to replicate this error is to do the following:

1. Create a multi-line proposal
2. Edit the proposal, adding a new line in the middle of the body text
3. Switch to view the proposal in a machine-translated language

https://staging.deploy.green.ca/processes/Policy2021/f/223/proposals/2593?locale=fr

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/ba087f3e-d0a1-41b5-8835-e833ea768fda)

https://staging.deploy.green.ca/processes/Policy2021/f/223/proposals/2585?locale=fr

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/1551af90-7929-4427-b5c2-952739bc0325)

It appears that the last line of the machine-translated text of a proposal, after an amendment is completed.  Here is an example:  https://staging.deploy.green.ca/processes/Policy2021/f/223/proposals/2588?locale=fr

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/35e534d5-82e2-45c1-805d-75a940b1ca4b)

There was also a strange case, where the machine translation created a new last line, saying that the proposal had been passed at the united nations:

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/80bad9ce-57c8-42ba-9c1d-8e87c20ebd54)

**Comment by paarals** [comment]
closed via #153
