### ISSUE TITLE
Machine-translated amendment titles not resolving special characters

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#156]
As shown in: https://staging.deploy.green.ca/processes/Policy2021/f/223/proposals/2592

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/0cd578fd-955d-4bf0-b932-6c55bb01de8d)

**Comment by paarals** [comment]
closed via #153
