### ISSUE TITLE
Accepting amendment in 'non-submitted' language uses machine-translated text

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#157]
To reproduce:
1. Go to amendment in non-submitted language
2. Click accept

Example: https://staging.deploy.green.ca/processes/Policy2021/f/223/proposals/2581?locale=fr

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/28431718-f4c0-4e73-9447-6468c1996135)

**Comment by paarals** [comment]
closed via #153
