### ISSUE TITLE
Offiical Proposals can only be modified in one language

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#159]
Official Proposals should accept amendments in either language.

To reproduce: 
1. Go to this proposal:
https://staging.deploy.green.ca/processes/Policy2021/f/223/proposals/2323?locale=fr

2. Attempt to make amendment ("Modifier proposition") 

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/b1a756f8-14ae-456b-a70d-ef4beb8a4e0d)

**Comment by paarals** [comment]
closed via #153
