### ISSUE TITLE
Moderated amendments remain visible and block further amendments

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#164]
What we see:  Moderated amendments remain visible in proposals and block further amendments
What we should see: Moderated amendments disappear from view for participants and further amendments are possible

Example: https://wedecide.green.ca/processes/create-proposals/f/457/proposals/4228

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/514dff71-97be-483c-93dd-69de3a34d752)

**Comment by paarals** [comment]
ok @BigSnicker, but i'm not sure if it's the correct workflow 
if an anmendment is repeted, the user should withdraw its amend. but we'll see if we can make it

**Comment by microstudi** [comment]
it's bug in Decidim, this are moderated proposals, cannot be seen anywhere except if they are amendment for other proposal in this page
solved
