### ISSUE TITLE
check comments machine translation

### ISSUE THREAD

**Issue by microstudi** [Green-Party-of-Canada-Members/gpc-decidim#17]
The machine translation works well for proposals, but is not currently enabled for comments. The EU site currently also does machine translation for comments, is there a way to easily add them?

- [ ] Check if comments are translated (it should)
- [ ] Configure comments translations if it is a straightforward job

Machine translation was configured here: https://github.com/Green-Party-of-Canada-Members/gpc-decidim/pull/14

**Comment by aitorlb** [comment]
I found that when leaving a comment after changing the locale to French, the `MachineTranslationFieldsJob` is failing. It works fine when leaving a comment when the locale is English tho.

I opened a PR https://github.com/Platoniq/decidim/pull/118
