### ISSUE TITLE
Copying a proposal

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#175]
There was a proposal that didn't get copied over from the Hothouse into the Workshop.

If you could copy this proposal -> https://wedecide.green.ca/processes/create-proposals/f/394/proposals/3818
Into this workshop -> https://wedecide.green.ca/processes/create-proposals/f/457/

**Comment by paarals** [comment]
Hi @BigSnicker, can i accept the original proposal? 
so i can import to the workshop?
![imatge](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/40388743/e28066fc-9734-4f5e-9209-edf3f23e2b9b)
it make sense that workflow, right? if not, @microstudi has to copy via bbdd

**Comment by microstudi** [comment]
I've copied manually

**Comment by BigSnicker** [comment]
Thank you!
