### ISSUE TITLE
Show timezone in dates 

### ISSUE THREAD

**Issue by microstudi** [Green-Party-of-Canada-Members/gpc-decidim#18]
User selected timezones for Assembly meetings and Convention meetings/agenda will be required, but I haven't had time to exhaustively identify where it's needed yet.

- [ ] Show timezone next to a date

- Ideally TZ styled: `America/Toronto` (requires some sort of configuration to let know Decidim which country to use). See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
- Easiest way: +5:00 GMT

**Comment by aitorlb** [comment]
@BigSnicker I have some questions:

> User selected timezones ...

- What is it mean by **selected**? Is the user asked to save their Time Zone somewhere? I know the postal code and country are saved during registration, but not the Time Zone. If this is not the case, we need to auto-detect the users' Time Zone. (I guess this is related to https://github.com/decidim/decidim/pull/5607#issuecomment-768098721)


> ... for Assembly meetings and Convention meetings/agenda will be required, ...

- The **meetings** part is clear. About **Convention** and **agenda**, do you mean **Conferences** and **program** ? (i.e. https://greensconnect.ca/conferences/AGM-2021-demonstration/program/271)

**Comment by microstudi** [comment]
user selected: i don't even understand myself. Just that the same timezone can be expressed in different ways depending on the country (ie: `Spain/Madrid` is the same as `France/Paris`).

An yes @BigSnicker is our John WIllson, so we can do as he says.

conventions/agenda === conferences/progarm yes

**Comment by BigSnicker** [comment]
Sorry, I was unclear. You should always tell me when I'm wrong, or if something is going to be a lot of work for little value, but I think the behaviour should ideally be:

1. TZ auto-detected at sign-up
2. TZ auto-populated as a preference in user data
3. Selectable from the user profile (e.g. in case of VPN or travel when they want a TZ that is not local)

I believe we talked about a more basic solution with Ivan that involved selectors/dropdowns on the pages themselves, so that could work as well, if there's a big difference in the work.

We could also just ask them to select their TZ preference at sign-up, if that's easier.

**Comment by microstudi** [comment]
@BigSnicker I'm not sure if it really adds value to show a user local time (autodetected or preference-selected). In my opinion this can lead to confusions easily, most people won't remember if they've chosen a different timezone from the organization. I would prefer a solution without any selector and just show the timezone next to a datetime.

**Comment by BigSnicker** [comment]
Ivan,

Are you saying that we just indicate the system timezone and ask everyone
to mentally adjust?

You can understand that, to take your example in Spain, asking you to work
according to a timezone three hours away (e.g. Central Russia, for you
guys), isn't hugely appreciated. We also have seniors who might not pick up
the TZ easily.  The potential confusion is not a great way to introduce
decidim to our most active members.

On a related note, how does calendar syncing work, via the URL?  Does that
already attach the system timezone?

Best regards,
John Willson (he/il)
Vice President and Director of the Green Party of Canada Fund |
Vice-président et directeur du Fonds du Parti vert du Canada

*Green Party of Canada | Parti vert du Canada*

+1.647.479.8478 (Ontario)

**Comment by aitorlb** [comment]
@BigSnicker I have trouble understanding point 2.

> 1. TZ auto-detected at sign-up
> 2. TZ auto-populated as a preference in user data
> 3. Selectable from the user profile (e.g. in case of VPN or travel when they want a TZ that is not local)

Is **user data** referring to **sign-up**, **user profile**, or something else.

Also, what if a person has an account already and does not select a TZ on their profile? Should we then show the organization TZ?

**Comment by BigSnicker** [comment]
Coming back to this.... I think we're going to have problems if we aren't able to show times in local (i.e. user-selected or browser-detected) timezones. This might be worth rethiking. @microstudi

**Comment by paarals** [comment]
@BigSnicker telegram:

> ![Image](https://user-images.githubusercontent.com/40388743/187483446-2a12c781-262b-4fbd-8a9e-0db7a93ac412.png)
> Is it possible to remove the -07:00? Ideally, it should read 09:30 - 12:00 PT

cc/ @microstudi
