### ISSUE TITLE
Export calendar not providing FQDN

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#180]
Clicking "Export calendar" on wedecide.green.ca produces this result:

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/d475e57a-44ef-4d6f-b17c-339600dd8ea1)

**Comment by paarals** [comment]
assigned to @microstudi

**Comment by BigSnicker** [comment]
![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/492b8f42-1d84-444b-a390-0a6b79507154)
