### ISSUE TITLE
Leadership Race

### ISSUE THREAD

**Issue by paarals** [Green-Party-of-Canada-Members/gpc-decidim#23]
**Acceptance criteria**

- [x] Tab in the main menu direct to Leadership Contest Forum

**Leadership Contest Forum Landing**
https://wedecide.experimental.greenparty.ca/processes/leadership
- [x] No changes
![LCC Website Planning - Frame 3](https://user-images.githubusercontent.com/40388743/183697272-95e9b7b7-4a39-4c45-a65a-eae6a2686c7b.jpg)

**The Contestants**
https://wedecide.experimental.greenparty.ca/processes/leadership/f/344/
- [x] Replace word Proposals with Contestants in Component: Contestants (Round One) in english
- [x] Hide All filters
- [x] Hide Authorship
- [x] Hide "View Proposal" button
- [x] Individualized configurable donate links are all URLs to off-site donation pages
- [x] Level below must link to the self-managed campaign assemblies (i.e. under "Leadership Campaigns")?
![LCC Website Planning - Frame 4](https://user-images.githubusercontent.com/40388743/183697807-bb23048d-b553-449f-a7cc-7b7b228909f7.jpg)

**Detailed proposal contsetant**
- [x] Donate to him/her
- [x] Acces to his/her campaing
![LCC Website Planning - Frame 12](https://user-images.githubusercontent.com/40388743/184863334-a35e16b5-3f90-40ea-a621-6931f40282a7.jpg)

**Events guide**
- [x] Enable iFrame component
- [x] Insert iframe wordpress (https://wedecide.experimental.greenparty.ca/admin/participatory_processes/leadership/components/350/edit)
![LCC Website Planning - Frame 5](https://user-images.githubusercontent.com/40388743/183698125-615659ce-68b8-4b99-b8d9-f5dc4fb3cda4.jpg)

**Events result**
https://staging.deploy.green.ca/processes/leadership/f/356/ 
- [x] Hide Origin filter
- [x] Hide Activity filter
- [x] Change "View proposal" button for "View results"
![LCC Website Planning - Frame 6](https://user-images.githubusercontent.com/40388743/183699062-fb1d7912-9b83-489f-8faf-1faa0b885ec4.jpg)

**Ask the contestants**
- [x] Needs definition
![LCC Website Planning - Frame 7](https://user-images.githubusercontent.com/40388743/183699270-e580927e-c4a7-4178-93ce-3038e2f7bead.jpg)

**Submit an Idea**
https://wedecide.experimental.greenparty.ca/processes/leadership/f/343/
- [x] Hide Origin filter
- [x] Hide Activity filter

![LCC Website Planning - Frame 8](https://user-images.githubusercontent.com/40388743/183699579-7988d48e-f2e1-4210-9cae-b3e2679da16f.jpg)

Staging: https://wedecide.experimental.greenparty.ca/processes/leadership

**Comment by paarals** [comment]
Hi @BigSnicker, 

> Tab in the main menu direct to Leadership Contest Forum
> Hide Origin filter
> Hide My activity filter

**Done**
![imatge](https://user-images.githubusercontent.com/40388743/181589681-26e3e89c-5d32-449e-bc60-1cf58bc43951.png)

> Replace word Proposals with Contestants in Component: Contestants (Round One)
To be done
> Replace word Proposals with Contestants in Component: Contestants (Round One)
Needs definition in french

> Contest Event Ideas 
Needs definition

**Comment by BigSnicker** [comment]
I need to provide input on this later today!

Immediate thoughts...

1. I think we have enough space to sneak in "Leadership Race Forum" in the top level menu, but up to you?
2. We need a better name for 'assemblies', which don't work in our context. I think "Organizations" might be best, except for where we have more specific words (e.g. Campaigns).

**Comment by BigSnicker** [comment]
Just realized we don't have Calendar in the top level navbar yet, so let's wait before adding in "Forum"

**Comment by BigSnicker** [comment]
Here are some comments on the next level down navigation in the Leadership Race

**The Contestants**
This is the 'offical' page for people looking for information on campaigns. It is fixed by the Leadership Committee and so shouldn't change during the campaign.
- [ ] Individualized configurable donate links are all URLs to off-site donation pages
- [ ] Level below must link to the self-managed campaign assemblies (i.e. under "Leadership Campaigns")?

**Events Guide**
This is probably an iFrame to a WordPress grid, unless Pau has any genius ideas.  However, iFrames still cannot be set based on language, yes?

**Event Results**
This is basically a searchable database of event results, so:
- [ ] viewers can filter for a specific event 
- [ ] viewers can filter for a specific contestant.
- [ ] either 'view results' at the end, or removing the button entirely

**Ask the Contestants** (low priority)
- [ ] A 'Proposal' module, except it's "Ask a question"

**Submit an Idea** (low priority)
- [ ] A 'Proposal' module, except it's "Submit an idea"

**Comment by paarals** [comment]
Hi @BigSnicker, I do rise some questions:

> The Contestants
> This is the 'offical' page for people looking for information on campaigns. It is fixed by the Leadership Committee and so shouldn't change during the campaign.
> 
> - [ ] Individualized configurable donate links are all URLs to off-site donation pages
> - [ ] Level below must link to the self-managed campaign assemblies (i.e. under "Leadership Campaigns")?
How do you imagine for that? right now is not possible to do, unless you use long description. 

> Events Guide
> This is probably an iFrame to a WordPress grid, unless Pau has any genius ideas. However, iFrames still cannot be set based on language, yes?
Yes, you can try it here: https://wedecide.experimental.greenparty.ca/admin/participatory_processes/leadership/components/350/edit

> Event Results
> This is basically a searchable database of event results, so:
i don't understand, this is a proposal or meeting component? and which will be the workflow?

thanks!

**Comment by BigSnicker** [comment]
Sorry, I didn't see these questions until now, for some reason.

So...

1. Long description is fine, but it would be really nice to have a 'donate' button at the higher level.
![image](https://user-images.githubusercontent.com/18507363/184431153-e38c5a02-4cb6-4d59-8b98-a79ee3fd46fc.png)
Here's a whacky idea.... what if we just changed "View Proposal" to "Donate" and triggered a new tab while it went to the long description?
2. I know the Awesome iFrames, I've used them a lot. But you can't have different iFrames for different languages, right?
3. This is just a Proposal component, with each proposal being posted by the Admin, but being "from" a contestant, with the "event" title and including a video in the content.
