### ISSUE TITLE
Error configuring any assembly in Dashboard

### ISSUE THREAD

**Issue by paarals** [Green-Party-of-Canada-Members/gpc-decidim#26]
**Describe the bug**
When I go to edit an assembly, an error comes. 

**To Reproduce**

1. Go to https://wedecide.experimental.greenparty.ca/admin/assemblies
2. Try to configure any assembly
3. See error

**Expected behavior**
I expect to be able to configure assemblies. 

**Screenshots**
![configure_assembly](https://user-images.githubusercontent.com/40388743/182408880-51f0c4a7-e8a2-4ec2-b217-8d98dc261a2b.gif)

**Comment by microstudi** [comment]
This was due a min-bug in a migration from decidim. should be solved now

**Comment by paarals** [comment]
Closed manually by @microstudi
