### ISSUE TITLE
Cannot access meeting details

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#27]
This is not urgent, and possibly just due to the assembly not being published, but I get a database error when trying to clickthrough to a dummy meeting.

Steps to reproduce: 

1. Go to https://wedecide.experimental.greenparty.ca/assemblies/contestant-a/f/345/
2. Click "Amazing meeting"

**Comment by microstudi** [comment]
fixed via https://github.com/Green-Party-of-Canada-Members/gpc-decidim/commit/12af75cc6c03706ce03d288e7183edc0a0a5078d
