### ISSUE TITLE
Leadership campaigns

### ISSUE THREAD

**Issue by paarals** [Green-Party-of-Canada-Members/gpc-decidim#28]
**Describe the solution you'd like**

As a user, in amazing canadian leadership race self-managed spaces (mother assembly): https://wedecide.experimental.greenparty.ca/assemblies/leadership-campaigns

- [x] I want to see a card of each contestant with photo, name and description (2 per row)
- [x] Remove help-text assembly
- [x] I want to be able to donate for contestant (button redirect to gpc donate)
- [x] I want to access specific campaign of contestants
- [x] Remove other assembly info

![Image](https://user-images.githubusercontent.com/40388743/183049135-a71ddbd3-86b9-43bb-a004-3c79a9d68cc2.jpg)

As a user, in self-managed spaces of contestants (child assembly): https://wedecide.experimental.greenparty.ca/assemblies/contestant-a

- [x] I want to see a short and long description
- [x] Change "The Assembly" to "The Campaign"
- [x] Remove help-text assembly
- [x] I want to be able to donate for contestant
- [x] I want to join meetings and comment blog posts
- [x] Remove other assembly info

![Image](https://user-images.githubusercontent.com/40388743/183049890-27767584-d58d-47ff-8951-636c55331205.jpg)

**Comment by BigSnicker** [comment]
Some additional tweaks.....

![image](https://user-images.githubusercontent.com/18507363/183330769-4a50bb01-6bc5-48d7-8aeb-9ba7486ca80a.png)

- [ ] Change "The Assembly" to "The Contestant"
- [ ] Is "Duration" just for information, or is it a counter that unpublishes the assembly after the duration is past? Hopefully it is just for information, in which it is fine and no action is required.

Also, at the top level of showing all the campaigns:

![image](https://user-images.githubusercontent.com/18507363/183330424-21137f57-54f9-424c-ac09-bbcf064d875c.png)

- [ ] ASSEMBILES -> CAMPAIGNS
- [ ] Remove 'Take Part" button entirely and give extra space to the short description?

**Comment by paarals** [comment]
hi @BigSnicker, thank you for your comments. 
I just have one question. right now, it looks like we have two "landings" for the leadership' campaign. This customized page:
![Image](https://user-images.githubusercontent.com/40388743/183049135-a71ddbd3-86b9-43bb-a004-3c79a9d68cc2.jpg)
does it refer to all assemblies, or is it a mother assembly?
If so, tweaks you put in the last top level of showing all campaigns shouldn't be there, because the page will look like your mock up (being a mother assembly). is that correct?

**Comment by BigSnicker** [comment]
- [ ] Potentially disable generic Assembly Help, unless we can do text specificaly for Leadership Campaigns?

![image](https://user-images.githubusercontent.com/18507363/183546994-b4bf55e2-4842-4b37-b05c-c3402a4f37bd.png)

**Comment by paarals** [comment]
> * [ ]  Potentially disable generic Assembly Help, unless we can do text specificaly for Leadership Campaigns?
> 
> 
> Are we able to write help text based on the ASSEMBLY TYPE?
> 
> ![image](https://user-images.githubusercontent.com/18507363/183546994-b4bf55e2-4842-4b37-b05c-c3402a4f37bd.png)

hi john, only is possible to customize a help-text for all assemblies. will be better to remove that

**Comment by BigSnicker** [comment]
Great, so let's disable that across the board, for assemblies and
processes. We can use a combination of announcements and live agent help
instead.

**Comment by BigSnicker** [comment]
Slight issue, how do manage different "home tabs" for different types of assemblies?

![image](https://user-images.githubusercontent.com/18507363/183792373-54222738-6db8-4262-a84b-3a353518c9df.png)

Ideally, we want

- [ ] The Campaigns (for parent assembly of all campaigns) (currently it's showing just 'The Campaign')
- [ ] The Campaign (for an assembly of a campaign)
- [ ] The Organization (for all other assemblies)

Is the best way to do this by using the Term Customizer module??

**Comment by paarals** [comment]
Hi @BigSnicker, as long as we don't have other assemblies, right now:
parent assembly > the campaigns
other assemblies > the campaign

**Comment by BigSnicker** [comment]
But we do potentially have a couple of other assemblies, though.

1. Leadership Contest Committee
2. Leadership Contest Arbiter

Best regards,
John Willson (he/il)
Co-President and Director of the Green Party of Canada Fund
Co-président et directeur du Fonds du Parti vert du Canada

*Green Party of Canada | Parti vert du Canada*

tel. +1.647.479.8478 (Ontario)

cell. +1.705.500.9010 (Ontario)

**Comment by paarals** [comment]
hi @BigSnicker, it's all in place. you can test it.
