### ISSUE TITLE
User Content - Machine Translation

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#3]
Hoping to add machine translation of user content.

We have created a free DeepL API account, but can use Google machine translate if that's easier to implement.

DeepL API docs: https://www.deepl.com/en/docs-api/
DeepL API Ruby Wrapper: https://github.com/wikiti/deepl-rb
DeepL API credentials: ......
DeepL subscription number: 603187

Note: We're not fixed on DeepL.  If Google Translate is much easier to implement, that will be fine

**Comment by microstudi** [comment]
As note and example of a currently operational machine translation implementation (using a custom EU system): https://futureu.europa.eu/processes/Health/f/3/proposals/537?toggle_translations=true

**Comment by BigSnicker** [comment]
Neat.  If it has an open API and is easier to implement because we can steal the decidim code, totally happy with that!

**Comment by BigSnicker** [comment]
The priority of this feature has gone up considerably, and we're doing a demonstration of the tool on our Sunday afternoon our time.

If there's any way this can be in place by then, that would be incredible... but there's no expectation for you to work over the weekend (of course!), so no worries if this isn't possible.  I just thought I'd raise it in case it's easy to do.

**Comment by BigSnicker** [comment]
I looked for an example of a decidim deployment that uses user content machine translation, but I couldn't find any.

Do you know of any decidim repository that has user machine translation working in production?
