### ISSUE TITLE
Select scopes/interests at time of registration

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#31]
Currently considering the following flow for new members (this would be required early September, when we would do the mass registration of 24,000+ members)

1. Members added via direct validation
2. Members receive email inviting them to register account
3. Members click on email to specify (@username, password and, optionally, select interests based on scopes)

**Comment by BigSnicker** [comment]
Sorta like this? https://github.com/decidim/decidim/issues/2265

**Comment by paarals** [comment]
hi @BigSnicker, 
as we were speaking in the meeting there is two possible way:

1. when user complete nickname and password, redirect to scopes interest page (no cost)
2. when user is completing nickname and password, also has the option to check scopes interest (that will required some budget)
