### ISSUE TITLE
403 errors

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#32]
I'm getting 403 errors in two cases...

1. Trying to activate leadership.green.ca  (This is probably something stupid I did. Certbot should already be updated, as it /system)
2. Confirming email authorizations (e.g. creating a new group by lca@johnwillson.com) http://wedecide.experimental.greenparty.ca/user_groups/confirmation?confirmation_token=QMpWJiCaaZq-B8oU4gmZ

Case #2 has been going on for at least a few days.

**Comment by paarals** [comment]
Hi @microstudi, second error is about confirmation token when you create a new group in your mail. 
1. create a group
2. try to confirm by email your group
3. get error

**Comment by BigSnicker** [comment]
I believe the 403 error was also experienced by people trying to accept
invitations to be administrators.

**Comment by BigSnicker** [comment]
Profiles also are giving 403s: http://wedecide.experimental.greenparty.ca/profiles/lenore_morris

**Comment by microstudi** [comment]
this looks like a bad nginx configuration. with the change of domain seems solved

**Comment by paarals** [comment]
tested and working
![imatge](https://user-images.githubusercontent.com/40388743/183853519-99354b6b-113b-49d7-baaf-1d6510fede58.png)

**Comment by BigSnicker** [comment]
> this looks like a bad nginx configuration.

Agreed.  This is what happens when you let amateurs do your nginx configurations!!

I'm going to have a very, very serious discussion with me about my performance.

(But thanks for fixing it!)
