### ISSUE TITLE
Campaigns appearing under "Home" tab, not "Leadership Campaigns" tab

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#39]
When I do the following:

1. Click on "Leadership Campaigns" top level tab
2. Click on any Leadership Campaign

Then I successsfully go into the Campaign Descriptions, but the top level navigation indicates that I've moved to the Home tab, as shown here:

![image](https://user-images.githubusercontent.com/18507363/184453848-8b246fa9-595d-4306-86b1-b869507f7e99.png)

**Comment by paarals** [comment]
done. you can test it: staging.gpc.pokecode.net/
