### ISSUE TITLE
Sign-off issues

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#41]
**Home/Watch Race Tab**
- [x] Watch Race iFrame in fullscreen/no border
- [x] Hide home tab

**Leadership Race Forum Tab**
- [x] "The Process" -> "The Race"
- [x] "See all proposals" -> "See all contestants" (twice)

**Leadership Race Events Tab**
- [x] Can the Race Forum Events Guide and Events Result  move to a new Leadership Events top-level navigation option?

**Leadership Campaigns Tab**
- [ ] Is there any issue that the hosted graphics broke? (See: Ivan Verges' campaign, but that's not the only one)

**Calendar**
- [x] Move calendar to the left of Policy Process
- [x] Colour coding isn't working for Meetings (should be white text on red) and External Events (should be white text on orange background)

**Things I'm thinking about (Possible next work, won't prevent sign-off)**
- [x] https://github.com/Green-Party-of-Canada-Members/gpc-decidim/issues/18

**Comment by paarals** [comment]
hi @BigSnicker, what about https://github.com/Green-Party-of-Canada-Members/gpc-decidim/issues/31?
maybe today we can discuss in a meeting this latest changes?

**Comment by BigSnicker** [comment]
Oooo yes.

I'm assuming that you'll do the easy/"free" version based on forwarding,
and that might be good enough for now.

Remember, if everyone's thrilled with your work, we can always ask for a
quote for another phase of work!

John

**Comment by microstudi** [comment]
What do you mean when you speak about forwarding? I'm lost here

**Comment by BigSnicker** [comment]
Rather than having scopes/interests selected on the registration page, you
discussed immediately forwarding the person to the profile page where
selection of scopes/interests normally is done.
