### ISSUE TITLE
Reporting not working for a blog post

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#42]
Reporting is generally working, but we found this case while joking around: https://leadership.green.ca/assemblies/leadership-contest-arbiter/f/347/posts/37

Clicking on the small flag does nothing.

**Comment by microstudi** [comment]
I don't see the post! something done with it?

**Comment by paarals** [comment]
> I don't see the post! something done with it?

there you have: https://leadership.green.ca/assemblies/leadership-contest-arbiter/f/347/posts/61

**Comment by BigSnicker** [comment]
Yes, that's the one!

**Comment by microstudi** [comment]
this looks like a Decidim bug. Reporting is not working for blog posts

**Comment by BigSnicker** [comment]
Not critical at all. I'll leave open. Should I report to metadecidim?

**Comment by paarals** [comment]
@BigSnicker shall we make this bugfix or we leave it to meta.decidim?
