### ISSUE TITLE
Replace "External Events" with "Events" and "Événements" in Calendar

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#43]
https://leadership.green.ca/calendar

- [x] Replace External Events for Events (en)
- [x] Replace External Events for Evénements (fr)

Also, there is no French version!

So "Events" should be "Événements"

No need to change wording in admin UI

And is there anyway to move "More / Download ICal" to use the "Sync calendar" style button?

**Comment by paarals** [comment]
hi @BigSnicker, translations done. but i don't get what do you mean by move "more/dowlonad ical"

**Comment by BigSnicker** [comment]
![image](https://user-images.githubusercontent.com/18507363/186761186-59c5edd2-b852-4f1c-a395-a9c41d3a80d6.png)

I mean the arrow on the right.  This is a possible future feature request. We love calendar synchronization, but "download iCal" is technical language that no one will understand and it's hidden behind the "more" button.

**Comment by BigSnicker** [comment]
So what needs to get done here is for:

**Comment by paarals** [comment]
translations done, @microstudi will do changes in the menu

**Comment by paarals** [comment]
done by @microstudi 
![imatge](https://user-images.githubusercontent.com/40388743/189596829-d3a5ff59-50f0-4fba-a843-d64db4e77363.png)
