### ISSUE TITLE
Idea! Can we dynamically set home tabs to assembly type?

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#44]
![image](https://user-images.githubusercontent.com/18507363/185810391-a4df7406-cab2-4f1b-ac4b-16509926348e.png)

Instead of "Assembly", "Process" or "Campaign", we could use "Assembly Type" quite well here.

**Comment by paarals** [comment]
i think that this is possible @BigSnicker, maybe @microstudi has another input

**Comment by BigSnicker** [comment]
We are now creating a lot of assemblies, from people who are seeing the platform and asking for a space.  But right now they're all coming up as "campaigns", whereas none of them are campaigns.

Using "Assembly type", or the last word in assembly type, would be a possible way to have it updated.
