### ISSUE TITLE
Notification on survey response?

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#45]
We're considering using surveys, such as here: https://leadership.green.ca/processes/leadership/f/362/

But is there no way to generate a notification, if a survey response is filed?

John.

**Comment by microstudi** [comment]
Done! via ENV var `QUESTIONNAIRE_NOTIFY_EMAILS`

**Comment by paarals** [comment]
done by QUESTIONNAIRE_NOTIFY_EMAILS
