### ISSUE TITLE
Meeting invitations allow admins to collect emails of all participants

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#47]
I generally thought, due to data privacy, that emails were kept from administrators.

However, this appears to display email address from the entire database, including blocked users, when inviting members to meetings:
![image](https://user-images.githubusercontent.com/18507363/186090870-bd34f99b-cda1-4a0d-bf0c-564c96ff45cc.png)

Is this a bug? Am I incorrect in assuming email addresses are supposed to be concealed?

John

**Comment by paarals** [comment]
Hi @microstudi, this happens here: https://staging.deploy.green.ca/admin/assemblies/fake-campaign-ivan/components/355/manage/meetings/134/registrations/invites

Desired solution: not show email from users in autocomplete

**Comment by microstudi** [comment]
I see, this is a bug and we can directly create a PR to Decidim core. I'll take care of that

**Comment by microstudi** [comment]
Fixed by https://github.com/openpoke/decidim/pull/14

**Comment by BigSnicker** [comment]
Perfect solution, @microstudi !
