### ISSUE TITLE
Update donation links

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#48]
Update algorithmically generated donation links to....

IF LANGUAGE IS ENGLISH - https://www.greenparty.ca/en/donations/firstname.lastname-en

IF LANGUAGE IS FRENCH - https://www.greenparty.ca/en/donations/firstname.lastname-fr

Note, we could just use the language code at the end, if possible.

FOR ANY LANGUAGE - https://www.greenparty.ca/en/donations/firstname.lastname-[TWO LETTER LANGUAGE CODE]

**Comment by microstudi** [comment]
fixed by https://github.com/Green-Party-of-Canada-Members/gpc-decidim/commit/171e8f97a4f22772c80b3bbc781c6436f58730e9

**Comment by BigSnicker** [comment]
Looks great.
