### ISSUE TITLE
Deleting fake campaigns

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#49]
How do we remove campaigns from here: https://leadership.green.ca/processes/leadership/f/344/?locale=en

Need to remove:

  | 2559 | John Willson |   | Not answered | - | 2 | 0 | 0 | 14/07/2022 23:11 |  
  | 2576 | Corrina Serda |   | Not answered | - | 0 | 0 | 0 | 24/08/2022 16:32 |  
  | 2575 | David Suzuki |   | Not answered | - | 0 | 0 | 0 | 24/08/2022 16:32 |  
  | 2573 | Samuel Moisan-Domm |   | Not answered | - | 0 | 0 | 0 | 24/08/2022 16:30 |  
  | 2574 | David Suzuki |   | Not answered | - | 0 | 0 | 0 | 24/08/2022 16:31 |  
  | 2560 | Natalie Odd |   | Not answered | - | 0 | 0 | 0 | 14/07/2022 23:14 |  
  | 2562 | Krystal Brooks |   | Not answered | - | 0 | 0 | 0 | 14/07/2022 23:51 |  
  | 2561 | Michael MacLean

**Comment by microstudi** [comment]
removed!

**Comment by BigSnicker** [comment]
One more Suzuki to still be removed! @microstudi

**Comment by BigSnicker** [comment]
Done!
