### ISSUE TITLE
Assembly admins can create new accounts

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#50]
![image](https://user-images.githubusercontent.com/18507363/187011540-5c143860-3cbc-4b63-942a-1c071d4823f4.png)

As per image.  I think we may need to disable allowing non-existing participants to be invited to meetings.

From: https://leadership.green.ca/admin/assemblies/fake-campaign/components/345/manage/meetings/130/registrations/invites

**Comment by microstudi** [comment]
we can disable this at application level if yo want

**Comment by BigSnicker** [comment]
Yes please. ENV?

**Comment by microstudi** [comment]
Fixed, uses ENV `DISABLE_EXTERNAL_INVITES`

**Comment by paarals** [comment]
closed by `DISABLE_EXTERNAL_INVITES`
