### ISSUE TITLE
Change Invitation Email 

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#55]
If possible, we discussed changing the invitation subject line from:

CURRENT: "Invitation instructions"

IDEAL :
"Your invitation to the Green Party of Canada's Participatory Democracy Platform"
"Votre invitation à la plateforme de démocratie participative du Parti Vert du Canada"

Also, we need to add in the words in square brackets:

-----------------

Hello Test.User,

You are invited to join **[the]** Green Party of Canada’s WeDecide **[website]**. You can accept this invitation through the link below.

[Accept invitation](http://leadership.green.ca/users/invitation/accept?invitation_token=FosD_W8zzZnhDyLTQzWm&invite_redirect=%2F)

This invitation will expire on October 03, 2022 18:22.

This account comes with your Green Party of Canada membership and will allow you to participate in our online participatory democratic processes, including policy development and internal elections.

If you don't want to accept the invitation, please ignore this email.

Your account won't be created until you access the link above and set your nickname and password.

**Comment by paarals** [comment]
solved via telegram
