### ISSUE TITLE
Imrpove rocket chat

### ISSUE THREAD

**Issue by paarals** [Green-Party-of-Canada-Members/gpc-decidim#61]
- [x] Enable sign up with civicrm in rocket chat
- [x] Solve error when changing statuts
- [x] Solve error when reporting

**Comment by microstudi** [comment]
Looks like the error is related to upgrading mongo to 5.0:
https://github.com/RocketChat/Rocket.Chat/issues/25185

**Comment by microstudi** [comment]
Solved by using the same user in `MONGO_URL` and `MONGO_OPLOG_URL` and, in mongo db:

```mongo
db.grantRolesToUser("rocketchat", [{role: "clusterAdmin", db: "admin"}])
```

**Comment by paarals** [comment]
> @BigSnicker 
Just testing rocket chat... there's a slight error with reporting. It's missing a slash after the FQDN...
![imatge](https://user-images.githubusercontent.com/40388743/193404501-949e278e-5b58-4e1c-8efd-af2edc986c3c.png)

**Comment by BigSnicker** [comment]
I've been reading up on the challenges of going from Mongo 4.4 to Mongo 5.0 for RocketChat and just wanted to check the following in our configuration.

Do we [set 'directConnection' in our Mongo DB URLs](https://discussion.scottibyte.com/t/upgrading-rocketchat-deployed-in-docker/69)?

Example:
      - MONGO_URL=mongodb://mongo:27017/rocketchat?replicaSet=rs0&directConnection=true
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local?replicaSet=rs0&directConnection=true

**Comment by microstudi** [comment]
We've followed a different approach here by not using the root user in the MONGO_OPLOG_URL. So, if everything in RocketChat works as expected, I wouldn't touch anything else.
@paarals I've added a slash in the the WAWA configuration, let's see if this solves the issue
