### ISSUE TITLE
Implement cloudflare CDN and/or S3 on Rocket.Chat assets

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#63]
This would be good, if it's easy to do!

(But this is getting out of decidim, so don't worry if you feel this is something that you shouldn't take on)

https://docs.rocket.chat/guides/administration/admin-panel/advanced-admin-settings/cdn

**Comment by microstudi** [comment]
If you are using cloudflare, you have a cdn in place already. I'd recommend not to worry about this

**Comment by BigSnicker** [comment]
I was worried about needing configuration to help CloudFlare distinguish between realtime messaging and static assets, but of COURSE CDN is smart enough to do that automatically now, I guess! lol
