### ISSUE TITLE
Importing accurate full names from CiviCRM database into Rocket.Chat

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#64]
Currently, CiviCRM's name field has varying formats.

"John Willson" could be imported into Rocket.Chat, via OAuth, as:

- "JohnWillson" 
- "jwillson" 
- "john@example.com"

... depending on whatever is in the CiviCRM database.

However, every user's Firstname and Lastname is correct, so we're wondering if we can import a more reliable full name to be used, unchangeably, in Rocket Chat. (e.g. rocketchat full name = civicrm first.name + " " + civicrm last.name)

@Laurence-Montgomery may be able to provide more information.

**Comment by Laurence-Montgomery** [comment]
For clarity, Civi's display name field is always correctly formatted. It is the Drupal username field that is not standardized.

- R.C is currently importing the **Drupal** username into the R.C. 'Name' field.
- Some Drupal usernames are not in the "First name Last name" format . 
- We do not currently allow Drupal users to change their username. (But when we do, then R.C seems to pick up the changes made to Drupal username into the R.C name field without a problem).
- The R.C username field appears to be local to R.C and can be changed by the R.C user without causing problems.

**Comment by microstudi** [comment]
Yes,@Laurence-Montgomery is right.
I dont' know if we can pick the name in Civi from drupal without any special ad-hoc development.
In Decidim, when using the Oauth method we also make a call to the CiviCRM API to get the name from there.
To replicate the same in Rocket Chat we should either modify the name sent by drupal or make RocketChat do the same and consulte the API. But both approaches require work and to modify the core of the application (drupal or Rocketchat).

**Comment by BigSnicker** [comment]
Having thought about it, I think the solution is to hand manage the cases
where someone signs up and has a strangly-formatted name.

Some of the names are perfectly fine.

Will discuss with Laurence today and I think we'll avoid any development
work.

Best regards,
John Willson (he/il)
Co-President and Director of the Green Party of Canada Fund
Co-président et directeur du Fonds du Parti vert du Canada

*Green Party of Canada | Parti vert du Canada*

tel. +1.647.479.8478 (Ontario)

cell. +1.705.500.9010 (Ontario)
