### ISSUE TITLE
Updating Rocket.Chat OAuth in CiviCRM with new domain

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#65]
I moved the Rocket.Chat domain from chat2.green.ca to chat.green.ca, but I think that broke the redirect URI populated in CiviCRM.

@Laurence-Montgomery might be able to make the change from chat2.green.ca to chat.green.ca in CiviCRM and then test the OAuth R.C authentication.

I'm leaving CiviCRM authentication for R.C in a broken state, anticipating that this can be fixed quickly.

**Comment by microstudi** [comment]
I've updated civicrm to allow the new domain. Should be working now.
Also updated the integration script in Decidim
