### ISSUE TITLE
Confusing dates on Assemblyy meeting pages

### ISSUE THREAD

**Issue by Laurence-Montgomery** [Green-Party-of-Canada-Members/gpc-decidim#70]
The date that appears beside the "Official meeting" text is not the date of the event/meeting. What does this date signify?

Three options 
1) Make it indicate the date of the event/meeting
2) Identify what it signifies if it represents some other important date. (Date event created?)
3) Remove it

**Comment by BigSnicker** [comment]
@Laurence-Montgomery Please include a link and/or (ideally and) screenshot to show what you're concerned about.

**Comment by BigSnicker** [comment]
Resolved using:

/* Removing creation date from meetings */
.author-data__extra span { display: none; }
