### ISSUE TITLE
Confusing Assembly menu title.

### ISSUE THREAD

**Issue by Laurence-Montgomery** [Green-Party-of-Canada-Members/gpc-decidim#71]
Could we replace the string "The Campaign" with "Info"? Can such a change be made locally (per assembly) or is it a global variable?
![image](https://user-images.githubusercontent.com/108595890/194169191-22f2e7ca-3ab9-4d9a-9ace-6748021f8b44.png)

**Comment by BigSnicker** [comment]
This question is entirely supplanted by this issue: https://github.com/Green-Party-of-Canada-Members/gpc-decidim/issues/44

Any update on that? It would solve this problem.
