### ISSUE TITLE
Old log-in screen in Assembly meeting  component registrations

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#72]
We made new events here within an assembly, for example here: https://leadership.green.ca/assemblies/events/f/379/meetings/150

However, if you're new and click on "join meeting", you get an old registration form:

![image](https://user-images.githubusercontent.com/18507363/194686542-ef991d73-c9d3-4cfd-b977-5242f5c99ad5.png)

Can we update that form to have the GPC OAuth listed, instead of "civiCRM"?
direct link: https://leadership.green.ca/assemblies/events/f/379/meetings/150
- [ ] Sign in with GPC account
- [ ] S'identifier au compte PVC

It's a little urgent, because an email to 24,000 members just went out, directing them to these events.

**Comment by paarals** [comment]
this can't be done with term customizer, so it must need @microstudi
