### ISSUE TITLE
Replace "Join Meeting" in meeting components

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#73]
"Join meeting" implies that you will join the meeting immediately.  We need to replace that with "Sign-up for meeting" or "s'inscrire à la réunion"

Mainly need this for Assembly component, but could use it across all meeting components: https://leadership.green.ca/assemblies/events/f/379/meetings/150

![image](https://user-images.githubusercontent.com/18507363/194686876-2f398109-c334-4aaf-a1cb-f87aac875be2.png)

**Comment by paarals** [comment]
done, for all across meetings
![imatge](https://user-images.githubusercontent.com/40388743/194843952-14524fa2-b673-4c87-aee6-bd352948602c.png)
