### ISSUE TITLE
Civi OAuth not working

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#83]
OAuth appears to no longer work, possibly due to a server reboot that was done when Civi had some technical issues.

Here is the error message:

![image](https://user-images.githubusercontent.com/18507363/210174018-5e1df316-8a92-4451-ae25-a36810ae54ee.png)

Normal account access to decidim is working fine (i.e. sign-in with non-OAuth decidim admin accounts) and Rocket.Chat OAuth also appears to continue to work without any problems.

**Comment by microstudi** [comment]
Permissions where disabled for anonymous users in the oauth2 server. They must be enabled

![image](https://user-images.githubusercontent.com/1401520/211069409-ef860ded-acb2-4fa7-aac1-9fc0e3a1b43f.png)
