### ISSUE TITLE
GUI editor (TextArea) does not capture all new lines or carriage returns

### ISSUE THREAD

**Issue by Laurence-Montgomery** [Green-Party-of-Canada-Members/gpc-decidim#88]
The proposal :

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/108595890/df079a2a-b9c7-4695-a63d-2d7a61d1f39a)

Gets rendered as this on the proposal card:

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/108595890/cfc2f701-0d64-4124-9d63-170abe197c05)

**Comment by BigSnicker** [comment]
Just an update that to capture that the recent fix enabled line breaks, but the editor does not capture sequential line breaks (i.e.. paragraphs) which makes for blocks of text that do not have spaces between paragraphs.

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/18d1a35b-eada-4ec5-8a4a-f1a7a9688509)

**Comment by BigSnicker** [comment]
Note... just an idea, but this problem might be resolvable if carriage returns/line breaks could be displayed as double line breaks.
