### ISSUE TITLE
Creating a bilingual form with Decidim Awesome and Term Customizer

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#89]
We're trying to create bilingual forms, using Term Customizer and Decidim Awesome (which is incredibly awesome!)

We see these instructions: (https://wedecide.green.ca/admin/decidim_awesome/config/proposal_custom_fields)
![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/02fba617-fa2a-41a1-b77e-da1a06014903)

And so try to create a new i18n term: (https://wedecide.green.ca/admin/term_customizer/sets/20/translations)
![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/b61e9902-ddca-4888-9aa4-17786a05f51d)

And put the i18n term in the form:  (https://wedecide.green.ca/admin/decidim_awesome/config/proposal_custom_fields)
![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/86c83f3a-3ecc-4476-b9d8-4bc826442efd)

But we're clearly doing something wrong.

Relatedly, we tried replacing the "Endorse" button with "Sponsor", with this attempt, which also seems to not work:  (https://wedecide.green.ca/admin/term_customizer/sets/20/translations)

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/01327ae9-7c39-4fb1-9ab1-290844cfd033)

**Comment by microstudi** [comment]
There's one thing that is not always well explained when using Term Customizer.
Everytime you add/modify a translation you need to "Clear Cache", otherwise you won't see it.
After clearing the cache, it works:
![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/1401520/3524f7d9-c4d7-46f2-a480-a2784a6f454d)

Cache is cleared with this button:
![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/1401520/f7bb7961-e123-4139-95f4-6eb309f70abc)

**Comment by BigSnicker** [comment]
I thought it might be something like that! lol. Thank you. Man, that isn't explained anywhere.

It reminds me of when The Barbarian was trying to update decidim, and microstudi said "But did you pre-compile the assets??".

No, I hadn't.

**Comment by BigSnicker** [comment]
![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/6959ebef-6100-4d28-8c20-1f16cd86c012)

**Comment by BigSnicker** [comment]
![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/219f5b9d-9d06-4a7b-9b91-8b488d4cef5e)

**Comment by BigSnicker** [comment]
Closed
