### ISSUE TITLE
Removing or fine-tuning the "Content might be automatically translated" announcement

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#90]
This announcement creates a lot of confusion, partly due to its prominence:

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/b6b61aa8-50d3-47f9-892e-991959675443)

Would it be easy to either:

1. Remove it entirely, in all circumstances or,
2. Only show it for pages that have been machine translated

We would also need guidance on what setting is appropriate, to ensure that "original" or hand-written text always overrides a machine-translated version, whenever there is a conflict.

**Comment by microstudi** [comment]
We've started by hiding the message. Is he easiest thing to do.

**Comment by microstudi** [comment]
I can confirm that "user" translations take precedence over "machine translations"

**Comment by paarals** [comment]
also @BigSnicker you can see the announcement in the component to express this disclaimer
