### ISSUE TITLE
Decidim Awesome custom fields interacting negatively with Diff Compare

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#91]
We were testing amendments to proposals created with the new custom form, and we got this:

Taken from: https://wedecide.green.ca/processes/create-proposals/f/394/proposals/3767

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/4de2a63d-8c56-4390-a7e8-91be233083e9)

We'll take any suggestions on how serious this is. We'll need to correct this before launch.

**Comment by BigSnicker** [comment]
Note: We have found a way to work around this.  So amendments will only be used in spaces that do not use custom fields in the form!  No need to work on this for now.

**Comment by microstudi** [comment]
@BigSnicker can we re-try this? I have the feeling that when you did this you didn't clear the term's customizer cache.

Just to be sure, thanks!
