### ISSUE TITLE
Redirecting root URL to Proposal Space

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#92]
We are considering eliminating the Navbar entirely, and having members work exclusively within a process.

We used decidim to hide the Navbar, and that worked well, but Decidim awesome doesn't allow us to redirect from the root URL.

Is it possible to redirect all queries to the root (e.g. wedecide.green.ca) to our proposal space (e.g. https://wedecide.green.ca/processes/create-proposals)?

**Comment by microstudi** [comment]
This is configured to do it with an ENV var. In Caprover go to `Production`-> `App Configs`:

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/1401520/ec0cbc4c-7b27-4ccc-bb0c-ff5b3389815f)

**Comment by microstudi** [comment]
BTW, it seems that the process you are redirecting people to is not published. Be aware!

**Comment by paarals** [comment]
@BigSnicker be aware that we apply the change of root. so if process is not published, users won't see nothing!

**Comment by BigSnicker** [comment]
Don't worry, we know.  (But thanks for making sure!) 

We've put up a maintenance message to warn people that it's under development.

**Comment by BigSnicker** [comment]
Closed
