### ISSUE TITLE
Official Proposals-only space?

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#93]
So I think we had this issue before, but we again have a space where we want only official proposals:

https://wedecide.green.ca/processes/create-proposals/f/415/

Didn't we do this last time by hiding the "new proposal" button from the participant's interface?

**Comment by paarals** [comment]
hi @BigSnicker, exactly, you can use this css which is in the awesome:
![imatge](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/40388743/e3355efb-f96d-4ac5-8739-73bb18d19ee5)
you just need to add a new case like that:
![imatge](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/40388743/21da04c8-fca9-46d5-87ea-fe6e006a84dc)
be sure you restrict the specific component. if you need 2 components to add this restriction, just put another new case

**Comment by BigSnicker** [comment]
Excellent, thank you!  Will test this soon!
