### ISSUE TITLE
Translation missing in civicrm confirmation account

### ISSUE THREAD

**Issue by paarals** [Green-Party-of-Canada-Members/gpc-decidim#94]
![imatge](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/40388743/2b7774a8-9e6d-4ba7-9d29-8680a8cb6e8e)

**Comment by BigSnicker** [comment]
![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/38062bbf-085a-4791-a249-c8380cc70639)

**Comment by BigSnicker** [comment]
Adjusting the above for GPC decidim...

invalid:
email_intro: There was an error in your authorization on the platform.
email_outro: Please contact support and tell them you did not receive the "CiviCRM Membership" authorization.
email_subject: Authorization error
notification_title: Invalid authorization with the "CiviCRM Membership" method
ok:
email_intro: You have been successfully authorized by the platform.
email_outro: You can now perform all actions on the platform that your authorization allows.  (Technical reference: CiviCRM)
email_subject: Authorization successful
notification_title: Successful authorization

**Comment by BigSnicker** [comment]
invalid:
email_intro: Une erreur s'est produite dans votre autorisation sur la plateforme.
email_outro: Veuillez contacter le support et leur dire que vous n'avez pas reçu l'autorisation "CiviCRM Membership".
email_subject: Erreur d'autorisation
notification_title: Autorisation non valide avec la méthode "CiviCRM Membership".
ok:
email_intro: Vous avez été autorisé avec succès par la plateforme.
email_outro: Vous pouvez maintenant effectuer toutes les actions sur la plate-forme que votre autorisation permet. (Référence technique : CiviCRM)
email_subject: Autorisation réussie
notification_title: Autorisation réussie

**Comment by BigSnicker** [comment]
Damn, I received this a short while ago, so the error is still happening.

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/51858e8b-0f45-4cad-a64e-af504b6940fb)

We are not currently using CiviCRM groups at all (i.e. and so don't know why this message is even occuring), so the solution could be any of the following:

1. Stop the use of CiviCRM groups
2. Suppress CiviCRM notifications
3. Fix the i18n tag
