### ISSUE TITLE
Carriage returns appearing ONLY in card/summary view

### ISSUE THREAD

**Issue by BigSnicker** [Green-Party-of-Canada-Members/gpc-decidim#96]
Gents,

Another strange thing came up in testing.  Carriage returns in Proposal body text are only visible in the card/summary view.  For example, this is how the body text was written for the test proposal (https://wedecide.green.ca/processes/create-proposals/f/394/proposals/3779), which shows up correctly in the card:

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/fa0dc558-d978-44b6-aae0-7a5f716278e8)

But this is how the body text looks when you click on the proposal:

![image](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/18507363/c02a24ac-02b3-440f-92d7-c59792419d22)

This would be problematic, as some by-law suggestions can be quite long.

**Comment by paarals** [comment]
made by css and put it custom styles: 
![imatge](https://github.com/Green-Party-of-Canada-Members/gpc-decidim/assets/40388743/c9e65ca8-75fc-4182-8752-145e6916112e)
/* Ensure line-break is honored even without HTML*/
.decidim_awesome-custom_fields dd {
  white-space: pre-line;
}
